# CI docker publish
#
# version 1.0.0
#
# see : https://universe.fugerit.org/src/docs/conventions/workflows/docker_publish.html

name: CI docker publish

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - develop
  release:
    types: [published]

# only allow one workflow at time on the give activation
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: fugerit-org/psychic-actions/maven-container-publish@mcp
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maven-options: -B clean package -P test,buildreact
          docker-context: 'fj-doc-playground-quarkus'
          docker-file: './fj-doc-playground-quarkus/Dockerfile'
          docker-platforms: linux/amd64,linux/arm64
          docker-tags: ${{ secrets.DOCKERHUB_USERNAME }}/fj-doc-playground-quarkus:${{ github.ref_name }},${{ secrets.DOCKERHUB_USERNAME }}/fj-doc-playground-quarkus:latest
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}

